version: 2.1

orbs:
  architect: giantswarm/architect@5.10.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: organization-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          executor: app-build-suite
          context: "architect"
          name: push-organization-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "organization-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-organization-operator-to-aws-app-collection
          context: architect
          app_name: "organization-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-organization-operator-to-azure-app-collection
          context: architect
          app_name: "organization-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-organization-operator-to-capa-app-collection
          context: architect
          app_name: "organization-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-organization-operator-to-vsphere-app-collection
          context: architect
          app_name: "organization-operator"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "organization-operator"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "organization-operator"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "organization-operator"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "organization-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-kvm-app-collection
          app_name: "organization-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-organization-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
