apiVersion: "v1"
appVersion: ""
description: "Chart holding organization-operator."
home: "https://github.com/giantswarm/organization-operator"
name: "organization-operator"
version: "1.6.1"
annotations:
  application.giantswarm.io/team: "bigmac"
  config.giantswarm.io/version: 1.x.x
